title: <p align="center"> Vignesh G </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vignesh-gopalakrishnan-00177577/">LinkedIn</a> |
  <a href="https://github.com/Vigneshkrisz">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Amazon as an Tech Ops Associate.
  Working in Energy domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
